Translation tutorial 3
rust-embedded/rust-raspberrypi-OS-tutorials pull request #167
Opened 2022-08-09 05:55 UTC by Jzow

### Description

<Please describe the issues fixed by this PR>

Related Issue: <Insert link here if applicable>

### Pre-commit steps

 - [ ] Tested on QEMU and real HW Rasperry Pi.
     - Not needed if it is just a README change or similar.
 - [ ] Ran `./contributor_setup.sh` followed by `./devtool ready_for_publish`
     - You'll need `Ruby` with `Bundler` and `NPM` installed locally.
     - If no Rust-related files were changed, `./devtool ready_for_publish_no_rust` can be used instead (faster).
     - This step is optional, but much appreciated if done.

2022-08-09 05:56 UTC, Jzow commented
#166

2022-08-09 06:49 UTC, andre-richter commented on 03_hacky_hello_world/README.CN.md
> +## 与上面不同
Please don't copy the diff in translations, but reference the auto-generated english version. See: https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials/blob/master/02_runtime_init/README.CN.md#%E7%9B%B8%E6%AF%94%E4%B9%8B%E5%89%8D%E7%9A%84%E5%8F%98%E5%8C%96diff

2022-08-09 06:50 UTC, andre-richter commented
Thanks! Do you have somebody for proofreading?

CC @colachg @readlnh

2022-08-13 07:17 UTC, colachg reviewed
Hi @Jzow , I have given some comments. Thanks for your work :)

2022-08-13 07:17 UTC, colachg commented on 03_hacky_hello_world/README.CN.md
> +- 紧急处理程序使用新的`println!()`以显示用户错误消息。
panic保留如何，我也不知道翻译成什么比较好。panic处理程序

2022-08-13 07:17 UTC, colachg commented on 03_hacky_hello_world/README.CN.md
> +  - 在本教程中，它检查字符串`Stopping here`，该字符串由`panic!()`在`main.rs`的末尾。
该字符由`main.rs`末尾的`panic!()`抛出。

2022-08-17 12:35 UTC, Jzow commented
@colachg Thank you for reviewing, I try to modify

2022-09-11 10:45 UTC, Jzow commented
@colachg Hi, I have tried to modify it. Can you review it again? If ok, I will continue to translate the following chapters

2022-09-11 11:00 UTC, colachg commented
> @colachg Hi, I have tried to modify it. Can you review it again? If ok, I will continue to translate the following chapters

Of course, can you please resolve all the comments that I left above if you have modified it or even you don't want to modify it?

2022-09-11 11:15 UTC, Jzow commented
> can you please resolve all the comments

please check, I have modified it and resolve all

2022-09-11 12:35 UTC, colachg approved these changes
/lgtm

2022-09-12 19:49 UTC, andre-richter commented on 03_hacky_hello_world/README.CN.md
> +## 与上面不同
This hasn’t been done it seems. Please change as suggested.

2022-09-12 19:50 UTC, andre-richter requested changes
Please see m comment regarding the diff section that was falsely marked as resolved.

2022-09-13 11:24 UTC, Jzow commented
Please check [the english version](README.md#diff-to-previous), which is kept up-to-date. 

Don't have to translate this sentence into Chinese? My understanding is that it can be linked to the English version of diff, which can be seen clearly by users. This sentence should be translated

If necessary, I will make another modification

@colachg What do you think?

2022-09-13 12:08 UTC, andre-richter commented
Okay for me to translate this sentence 👍

2022-09-19 06:55 UTC, andre-richter commented
Please open one PR per chapter. That makes reviewing easier for others.

It seems that for tutorial 3, you still have the English sentence for
> Please check [the english version](README.md#diff-to-previous), which is kept up-to-date.

In tutorial 4, it is translated already.

2022-09-22 07:37 UTC, merged

2022-09-22 07:37 UTC, andre-richter commented
Thanks a lot!